version: '3'

services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pwd
    ports:
      - "5432:5432"
#
#  backend:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    volumes:
#      - ./:/home/www/app
#    depends_on:
#      - postgres
#
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./static:/var/html/static/
#    depends_on:
#      - backend
