# Generated by Django 3.2 on 2021-05-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210505_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='tittle',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
