# Generated by Django 3.2 on 2021-05-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('title',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tittle',
            new_name='title',
        ),
    ]
