# Generated by Django 3.2 on 2021-05-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='display_name',
        ),
    ]
