# Generated by Django 3.2 on 2021-05-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_unit_ingredient_dimension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
