# Generated by Django 3.2.2 on 2021-05-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20210512_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='background_color',
        ),
    ]
